Organize project structure and add iosApp host

diff --git a/.github/workflows/ios_build.yml b/.github/workflows/ios_build.yml
--- a/.github/workflows/ios_build.yml
+++ b/.github/workflows/ios_build.yml
@@ -26,15 +26,15 @@ jobs:
       - name: List files for debug
         run: ls -R
 
-      - name: Install Cocoapods
-        run: |
-          if [ -f "iosApp/Podfile" ]; then
-            cd iosApp
-            pod install
-          else
-            echo "Error: Podfile not found in iosApp directory"
-            exit 1
-          fi
+      # - name: Install Cocoapods
+      #   run: |
+      #     if [ -f "iosApp/Podfile" ]; then
+      #       cd iosApp
+      #       pod install
+      #     else
+      #       echo "Error: Podfile not found in iosApp directory"
+      #       exit 1
+      #     fi
 
       - name: Build Framework
         run: ./gradlew :composeApp:assembleDebugAppleFrameworkForXcode
